[2025-03-27T18:32:41.818+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T18:32:41.886+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelamento.get_all_data scheduled__2025-03-27T18:00:00+00:00 [queued]>
[2025-03-27T18:32:41.935+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelamento.get_all_data scheduled__2025-03-27T18:00:00+00:00 [queued]>
[2025-03-27T18:32:41.936+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 4
[2025-03-27T18:32:42.029+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): get_all_data> on 2025-03-27 18:00:00+00:00
[2025-03-27T18:32:42.154+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1219) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-27T18:32:42.159+0000] {standard_task_runner.py:72} INFO - Started process 1221 to run task
[2025-03-27T18:32:42.158+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_inaturalist_data_atropelamento', 'get_all_data', 'scheduled__2025-03-27T18:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/inaturalist_dag.py', '--cfg-path', '/tmp/tmpxgy4j9ql']
[2025-03-27T18:32:42.169+0000] {standard_task_runner.py:105} INFO - Job 231: Subtask get_all_data
[2025-03-27T18:32:42.466+0000] {task_command.py:467} INFO - Running <TaskInstance: get_inaturalist_data_atropelamento.get_all_data scheduled__2025-03-27T18:00:00+00:00 [running]> on host 804b404afff8
[2025-03-27T18:32:43.114+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_inaturalist_data_atropelamento' AIRFLOW_CTX_TASK_ID='get_all_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T18:00:00+00:00'
[2025-03-27T18:32:43.156+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T18:32:43.282+0000] {inaturalist_dag.py:301} INFO - Maximum id 264497584 for the request
[2025-03-27T18:32:44.435+0000] {inaturalist_dag.py:317} INFO - Got 0 results
[2025-03-27T18:32:44.612+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-27T18:32:44.670+0000] {python.py:240} INFO - Done. Returned value was: []
[2025-03-27T18:32:44.918+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T18:32:44.921+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=get_inaturalist_data_atropelamento, task_id=get_all_data, run_id=scheduled__2025-03-27T18:00:00+00:00, execution_date=20250327T180000, start_date=20250327T183241, end_date=20250327T183244
[2025-03-27T18:32:45.131+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-27T18:32:45.441+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-27T18:32:45.448+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
