[2025-03-26T00:11:10.305+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T00:11:10.373+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: teste_ingestao_dados_fakes.gerar_dados_fakes manual__2025-03-26T00:10:54.210084+00:00 [queued]>
[2025-03-26T00:11:10.408+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: teste_ingestao_dados_fakes.gerar_dados_fakes manual__2025-03-26T00:10:54.210084+00:00 [queued]>
[2025-03-26T00:11:10.414+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-26T00:11:10.498+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): gerar_dados_fakes> on 2025-03-26 00:10:54.210084+00:00
[2025-03-26T00:11:10.578+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=63) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-26T00:11:10.579+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'teste_ingestao_dados_fakes', 'gerar_dados_fakes', 'manual__2025-03-26T00:10:54.210084+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/teste_ingestao_dag.py', '--cfg-path', '/tmp/tmpg4pdf_3w']
[2025-03-26T00:11:10.583+0000] {standard_task_runner.py:72} INFO - Started process 65 to run task
[2025-03-26T00:11:10.587+0000] {standard_task_runner.py:105} INFO - Job 159: Subtask gerar_dados_fakes
[2025-03-26T00:11:10.879+0000] {task_command.py:467} INFO - Running <TaskInstance: teste_ingestao_dados_fakes.gerar_dados_fakes manual__2025-03-26T00:10:54.210084+00:00 [running]> on host d76bf457b908
[2025-03-26T00:11:11.389+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='teste_ingestao_dados_fakes' AIRFLOW_CTX_TASK_ID='gerar_dados_fakes' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T00:10:54.210084+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T00:10:54.210084+00:00'
[2025-03-26T00:11:11.420+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-26T00:11:11.460+0000] {teste_ingestao_dag.py:45} INFO - Dados gerados: [{'observation_id': 1, 'species_guess': 'Capivara', 'observed_on': '2025-03-25', 'latitude': -23.55, 'longitude': -46.63}, {'observation_id': 2, 'species_guess': 'Tamanduá', 'observed_on': '2025-03-24', 'latitude': -15.78, 'longitude': -47.93}]
[2025-03-26T00:11:11.461+0000] {python.py:240} INFO - Done. Returned value was: [{'observation_id': 1, 'species_guess': 'Capivara', 'observed_on': '2025-03-25', 'latitude': -23.55, 'longitude': -46.63}, {'observation_id': 2, 'species_guess': 'Tamanduá', 'observed_on': '2025-03-24', 'latitude': -15.78, 'longitude': -47.93}]
[2025-03-26T00:11:11.566+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-26T00:11:11.572+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=teste_ingestao_dados_fakes, task_id=gerar_dados_fakes, run_id=manual__2025-03-26T00:10:54.210084+00:00, execution_date=20250326T001054, start_date=20250326T001110, end_date=20250326T001111
[2025-03-26T00:11:11.711+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-26T00:11:11.904+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-26T00:11:11.909+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
