[2025-03-27T18:06:50.832+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T18:06:52.048+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelamento.get_all_data manual__2025-03-27T18:01:19.420078+00:00 [queued]>
[2025-03-27T18:06:52.220+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelamento.get_all_data manual__2025-03-27T18:01:19.420078+00:00 [queued]>
[2025-03-27T18:06:52.254+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2025-03-27T18:06:52.761+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): get_all_data> on 2025-03-27 18:01:19.420078+00:00
[2025-03-27T18:06:53.023+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=849) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-27T18:06:53.067+0000] {standard_task_runner.py:72} INFO - Started process 878 to run task
[2025-03-27T18:06:53.156+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_inaturalist_data_atropelamento', 'get_all_data', 'manual__2025-03-27T18:01:19.420078+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/inaturalist_dag.py', '--cfg-path', '/tmp/tmpoxd0nbhx']
[2025-03-27T18:06:53.305+0000] {standard_task_runner.py:105} INFO - Job 208: Subtask get_all_data
[2025-03-27T18:06:55.440+0000] {task_command.py:467} INFO - Running <TaskInstance: get_inaturalist_data_atropelamento.get_all_data manual__2025-03-27T18:01:19.420078+00:00 [running]> on host 804b404afff8
[2025-03-27T18:06:57.486+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_inaturalist_data_atropelamento' AIRFLOW_CTX_TASK_ID='get_all_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T18:01:19.420078+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T18:01:19.420078+00:00'
[2025-03-27T18:06:57.533+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T18:06:58.134+0000] {inaturalist_dag.py:301} INFO - Maximum id 264497584 for the request
[2025-03-27T18:06:59.408+0000] {job.py:229} INFO - Heartbeat recovered after 11.69 seconds
[2025-03-27T18:07:01.790+0000] {inaturalist_dag.py:317} INFO - Got 0 results
[2025-03-27T18:07:02.377+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-27T18:07:02.646+0000] {python.py:240} INFO - Done. Returned value was: []
[2025-03-27T18:07:04.130+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T18:07:04.181+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=get_inaturalist_data_atropelamento, task_id=get_all_data, run_id=manual__2025-03-27T18:01:19.420078+00:00, execution_date=20250327T180119, start_date=20250327T180652, end_date=20250327T180704
[2025-03-27T18:07:05.009+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-27T18:07:06.182+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-27T18:07:06.391+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
