[2025-03-25T19:29:52.749+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T19:29:52.757+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: teste_ingestao_dados_fakes.gerar_dados_fakes manual__2025-03-25T19:29:49.543550+00:00 [queued]>
[2025-03-25T19:29:52.760+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: teste_ingestao_dados_fakes.gerar_dados_fakes manual__2025-03-25T19:29:49.543550+00:00 [queued]>
[2025-03-25T19:29:52.760+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-25T19:29:52.764+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): gerar_dados_fakes> on 2025-03-25 19:29:49.543550+00:00
[2025-03-25T19:29:52.771+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=91) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-25T19:29:52.772+0000] {standard_task_runner.py:72} INFO - Started process 93 to run task
[2025-03-25T19:29:52.772+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'teste_ingestao_dados_fakes', 'gerar_dados_fakes', 'manual__2025-03-25T19:29:49.543550+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/teste_ingestao_dag.py', '--cfg-path', '/tmp/tmpfmbbl7pk']
[2025-03-25T19:29:52.775+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask gerar_dados_fakes
[2025-03-25T19:29:52.801+0000] {task_command.py:467} INFO - Running <TaskInstance: teste_ingestao_dados_fakes.gerar_dados_fakes manual__2025-03-25T19:29:49.543550+00:00 [running]> on host 5433644a7716
[2025-03-25T19:29:52.834+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='teste_ingestao_dados_fakes' AIRFLOW_CTX_TASK_ID='gerar_dados_fakes' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T19:29:49.543550+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-25T19:29:49.543550+00:00'
[2025-03-25T19:29:52.835+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-25T19:29:52.836+0000] {python.py:240} INFO - Done. Returned value was: [{'observation_id': 1, 'species_guess': 'Capivara', 'observed_on': '2025-03-25', 'latitude': -23.55, 'longitude': -46.63}, {'observation_id': 2, 'species_guess': 'Tamandu√°', 'observed_on': '2025-03-24', 'latitude': -15.78, 'longitude': -47.93}]
[2025-03-25T19:29:52.847+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-25T19:29:52.847+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=teste_ingestao_dados_fakes, task_id=gerar_dados_fakes, run_id=manual__2025-03-25T19:29:49.543550+00:00, execution_date=20250325T192949, start_date=20250325T192952, end_date=20250325T192952
[2025-03-25T19:29:52.871+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-25T19:29:52.884+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
